Add nullalbe exchange on company search search
MatthiWare/FinancialModelingPrep.NET pull request #35
Opened 2022-06-10 15:54 UTC by walterfranssen

2022-06-10 17:29 UTC, Matthiee requested changes
Thank you for the PR, it looks good!
However some small changes are needed before it can be merged.

2022-06-10 17:29 UTC, Matthiee commented on Tests/CompanyValuation/CompanyValuationTests.cs
> +            var result = await api.SearchByTickerAsync("AGS", null, 5);
```suggestion
            var result = await api.SearchByTickerAsync("AGS", limit: 5);
```

2022-06-15 10:36 UTC, walterfranssen commented
Do you know why 128 test are failing?

2022-06-15 15:07 UTC, Matthiee commented
@walterfranssen There is only 1 unit test failing see my suggestion here: https://github.com/MatthiWare/FinancialModelingPrep.NET/pull/35/files#r894752437

After that it looks like it can be merged!

2022-06-16 11:47 UTC, walterfranssen commented
I change the symbol too AAPL, is in my subscription. Works on my machine :)

2022-06-16 16:29 UTC, Matthiee approved these changes

2022-06-16 16:30 UTC, merged

2022-06-16 16:31 UTC, Matthiee commented
@walterfranssen thank you for your contribution!